### ISSUE TITLE
Cannot connect to any cluster, local or remote when connected to repl from cursive.

### ISSUE THREAD

**Issue by LukeDefeo** [HCADatalab/powderkeg#12]
Hi im trying to get started, When i do 

    lein repl
    (keg/connect! "local[*]")

It works but when i try from a  repl connected to cursive, I get an error. I have tried connecting to a lein repl as well as an nrepl.

Stacktrace is below but the interesting part is think is:

> CompilerException java.net.URISyntaxException: Illegal character in path at index 27: file:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar, compiling:

(keg/connect! "local[*]")
17/01/19 14:36:47 INFO SparkContext: Running Spark version 1.5.2
17/01/19 14:36:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/01/19 14:36:48 INFO SecurityManager: Changing view acls to: luked
17/01/19 14:36:48 INFO SecurityManager: Changing modify acls to: luked
17/01/19 14:36:48 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(luked); users with modify permissions: Set(luked)
17/01/19 14:36:48 INFO Slf4jLogger: Slf4jLogger started
17/01/19 14:36:48 INFO Remoting: Starting remoting
17/01/19 14:36:48 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.0.25:50849]
17/01/19 14:36:48 INFO Utils: Successfully started service 'sparkDriver' on port 50849.
17/01/19 14:36:48 INFO SparkEnv: Registering MapOutputTracker
17/01/19 14:36:48 INFO SparkEnv: Registering BlockManagerMaster
17/01/19 14:36:48 INFO DiskBlockManager: Created local directory at /private/var/folders/wl/y9791wh568jcphhq_sx_zmrskgs4x4/T/blockmgr-c0d088fc-7bc4-4858-ad89-20ce746f5d18
17/01/19 14:36:48 INFO MemoryStore: MemoryStore started with capacity 1966.1 MB
17/01/19 14:36:48 INFO HttpFileServer: HTTP File server directory is /private/var/folders/wl/y9791wh568jcphhq_sx_zmrskgs4x4/T/spark-05fa0eaa-ff69-4b83-8147-c0576c7a7c9b/httpd-dc5e363d-e226-4947-afe7-7830b059782a
17/01/19 14:36:48 INFO HttpServer: Starting HTTP Server
17/01/19 14:36:48 INFO Utils: Successfully started service 'HTTP file server' on port 50850.
17/01/19 14:36:48 INFO SparkEnv: Registering OutputCommitCoordinator
17/01/19 14:36:48 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
17/01/19 14:36:48 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
17/01/19 14:36:49 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
17/01/19 14:36:49 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
17/01/19 14:36:49 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
17/01/19 14:36:49 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
17/01/19 14:36:49 INFO Utils: Successfully started service 'SparkUI' on port 4046.
17/01/19 14:36:49 INFO SparkUI: Started SparkUI at http://192.168.0.25:4046
17/01/19 14:36:49 INFO SparkContext: Added JAR file:/Users/luked/.m2/repository/org/apache/maven/maven-aether-provider/3.0.4/maven-aether-provider-3.0.4.jar at http://192.168.0.25:50850/jars/maven-aether-provider-3.0.4.jar with timestamp 1484836609225
17/01/19 14:36:49 INFO SparkContext: Added JAR file:/Users/luked/.m2/repository/hcadatalab/powderkeg/0.4.2/powderkeg-0.4.2.jar at http://192.168.0.25:50850/jars/powderkeg-0.4.2.jar with timestamp 1484836609226
17/01/19 14:36:49 INFO SparkContext: Added JAR file:/Users/luked/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar at http://192.168.0.25:50850/jars/maven-model-3.0.4.jar with timestamp 1484836609227
17/01/19 14:36:49 INFO SparkContext: Added JAR file:/Users/luked/.m2/repository/com/cemerick/pomegranate/0.3.0/pomegranate-0.3.0.jar at http://192.168.0.25:50850/jars/pomegranate-0.3.0.jar with timestamp 1484836609228
17/01/19 14:36:49 INFO SparkContext: Added JAR file:/Users/luked/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar at http://192.168.0.25:50850/jars/objenesis-2.1.jar with timestamp 1484836609228
17/01/19 14:36:49 ERROR SparkContext: Error initializing SparkContext.
java.net.URISyntaxException: Illegal character in path at index 27: file:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.spark.SparkContext.addJar(SparkContext.scala:1628)
	at org.apache.spark.SparkContext$$anonfun$14.apply(SparkContext.scala:480)
	at org.apache.spark.SparkContext$$anonfun$14.apply(SparkContext.scala:480)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:480)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:61)
	at powderkeg.core$connect_BANG_$fn__2321.invoke(core.clj:94)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.alterRoot(Var.java:303)
	at clojure.core$alter_var_root.invokeStatic(core.clj:5299)
	at clojure.core$alter_var_root.doInvoke(core.clj:5294)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at powderkeg.core$alter_var.invokeStatic(core.clj:73)
	at powderkeg.core$alter_var.doInvoke(core.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at powderkeg.core$connect_BANG_.invokeStatic(core.clj:80)
	at powderkeg.core$connect_BANG_.invoke(core.clj:75)
	at powder_key_scratch.core$eval2691.invokeStatic(core.clj:4)
	at powder_key_scratch.core$eval2691.invoke(core.clj:4)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at user$eval2687.invokeStatic(form-init2520225697570650160.clj:1)
	at user$eval2687.invoke(form-init2520225697570650160.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
	at clojure.main$repl$fn__7417.invoke(main.clj:258)
	at clojure.main$repl.invokeStatic(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:174)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__648.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__693$fn__696.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__688.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17/01/19 14:36:49 INFO SparkUI: Stopped Spark web UI at http://192.168.0.25:4046
17/01/19 14:36:49 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/01/19 14:36:49 ERROR Utils: Uncaught exception in thread nREPL-worker-0
java.lang.NullPointerException
	at org.apache.spark.network.netty.NettyBlockTransferService.close(NettyBlockTransferService.scala:152)
	at org.apache.spark.storage.BlockManager.stop(BlockManager.scala:1228)
	at org.apache.spark.SparkEnv.stop(SparkEnv.scala:100)
	at org.apache.spark.SparkContext$$anonfun$stop$12.apply$mcV$sp(SparkContext.scala:1749)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1185)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:1748)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:593)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:61)
	at powderkeg.core$connect_BANG_$fn__2321.invoke(core.clj:94)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.alterRoot(Var.java:303)
	at clojure.core$alter_var_root.invokeStatic(core.clj:5299)
	at clojure.core$alter_var_root.doInvoke(core.clj:5294)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at powderkeg.core$alter_var.invokeStatic(core.clj:73)
	at powderkeg.core$alter_var.doInvoke(core.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at powderkeg.core$connect_BANG_.invokeStatic(core.clj:80)
	at powderkeg.core$connect_BANG_.invoke(core.clj:75)
	at powder_key_scratch.core$eval2691.invokeStatic(core.clj:4)
	at powder_key_scratch.core$eval2691.invoke(core.clj:4)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at user$eval2687.invokeStatic(form-init2520225697570650160.clj:1)
	at user$eval2687.invoke(form-init2520225697570650160.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
	at clojure.main$repl$fn__7417.invoke(main.clj:258)
	at clojure.main$repl.invokeStatic(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:174)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__648.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__693$fn__696.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__688.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
CompilerException java.net.URISyntaxException: Illegal character in path at index 27: file:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar, compiling:(/Users/luked/Git/learn/powder-key-scratch/src/powder_key_scratch/core.clj:4:1) 
17/01/19 14:36:49 INFO SparkContext: Successfully stopped SparkContext

**Comment by cgrand** [comment]
Fix available in 0.4.3
